QUESTIONS = [
  "I can remain balanced in my emotion irrespective of whether I succeed or fail.",
  "I can easily revise my plans without accepting defeat when I get stuck up.",
  "I usually get back to my cheerful self pretty soon no matter what failures occur in my life.",
  "When the situation is very demanding I can pull up myself and handle all of it efficiently.",
  "I do not waste my time on lamenting over the past however bad it might have been.",
  "During times of trouble I sink with feeling helpless.",
  "I easily breakdown at the crisis and it takes longer time for me recover myself.",
  "People say that I have a strong heart which can withstand any disappointment.",
  "I can recover from bad mood quickly and easily after facing any sad event.",
  "I suffocate a lot when facing problems",
  "When in trouble I get impatient and am impulsive.",
  "Challenges are not problems but are opportunities for rising to the occasion.",
  "My efficiency significantly drops down at difficult times.",
  "When I fight, I fight only to have the gusto feelings it gives me.",
  "When I am in a difficult situation, I can usually find my out of it.",
  "I don’t venture on any project where I had failed earlier.",
  "I cannot recover from frustration for long time.",
  "Life will be barren if there were no problem at all.",
  "I stay cool even when things don’t go the way I expect.",
  "I can handle any critical situation with confidence.",
  "Nothing can stop me from proceeding on any task once I begin my work",
  "Even a severe setback can only make me bend but never break.",
  "If I am defeated, I first think how to bounce back.",
  "I usually get confused about which way to move when I face problems.",
  "Problems enrich me with new resources.",
  "Whether disappointment is small or big I feel miserable.",
  "The greater the problem, the greater my effort to solve it.",
  "I feel weak to begin ventures due to past frustrations.",
  "Past failures cannot deter me.",
  "Failures never deter my efforts for long.",
];